set(PLATFORM_REQUIRED_DEPS LibAndroidJNI OpenGLES EGL LibZip)
set(PLATFORM_OPTIONAL_DEPS_EXCLUDE CEC)
set(APP_RENDER_SYSTEM gles)
list(APPEND PLATFORM_OPTIONAL_DEPS LibDovi)
list(APPEND PLATFORM_OPTIONAL_PACKAGES LibAACS LibBDPlus)

# Store SDK compile version
set(TARGET_SDK 37)
# Minimum supported SDK version
set(TARGET_MINSDK 24)

set(${CORE_SYSTEM_NAME}_SEARCH_CONFIG NO_DEFAULT_PATH CACHE STRING "")
